name: Release
on:
  repository_dispatch:
    types: [release]

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit updated submodule
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Release ${{ github.event.client_payload.version }}
          token: ${{ secrets.PAT }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.client_payload.version }}
